sequenceDiagram
    %% Scenario 2 - User logs in to the application (correct credentials)
    autonumber
    actor User
    participant LoginUI as &lt;&lt;boundary&gt;&gt;<br>LoginUI
    participant UserC as &lt;&lt;control&gt;&gt;<br>UserController
    participant DataC as &lt;&lt;control&gt;&gt;<br>DatabaseController
    participant Data as &lt;&lt;entity&gt;&gt;<br>Database
    participant Profile as &lt;&lt;entity&gt;&gt;<br>Profile
    User    ->>+    LoginUI : login()
    LoginUI ->>+    UserC   : login()
    UserC   ->>+    UserC   : build_user_credentials()
    UserC   ->>+    DataC   : match_profile()
    DataC   -->     Data    : match credentials
    DataC   -->     Profile : new Profile(...)
    DataC   -->>-   UserC   : return Profile
    UserC   -->>-   UserC   : return Profile
    UserC   -->>-   LoginUI : resolve login
    LoginUI -->>-   User    : redirect to /dashboard